### PR TITLE
Husky hooks to pre-commit and pre-push configure to work with lerna

### LINKED ISSUE #217: Integrate prettier
Would be nice to add this: https://github.com/prettier/prettier, maybe with a git hook as well
This can be used for inspiration: https://github.com/aragon/aragon

### LINKED ISSUE #218: Pre-commit hook for linting
We can use husky and lint staged to lint before committing:
https://github.com/okonet/lint-staged

Extract bits out of https://github.com/aragon/aragon.js/pull/221.

### PR DESCRIPTION
**Pull request by 0xGabi**
Closes #218 , closes #217

### CODE REVIEW

**Comment by 0x6431346e** [comment]
Closes #217

Looks good btw!
I took a quick look, but I think we should wait with this and merge #123 and other bigger PRs before. 
I should be much easier to update this PR (mostly doing `npx eslint --fix`), than the others.

**Comment by 0xGabi** [comment]
Now that #123 was merge this PR was unblocked. Is relevant still?

**Comment by sohkai** [comment]
@0xGabi Actually we had a similar PR #217 opened as well, but we've stalled this primarily to wait for a aragon-global config for JS (babel, eslint, etc.).

I've wanted it for a long time, it _is_ coming _soon_ 😄. But in the mean time I'd like to keep this and #217 open to help guide the standardization effort :).

**Comment by sohkai** [comment]
@0xGabi Going to close this for now and extract the useful bits out once we've integrated prettier and etc. :).

**Pull request closed without merging**
