### PR TITLE
Add new MANAGE_PROFILE_ROLE for DAO Profiles

### PR DESCRIPTION
**Pull request by Evalir**
**Changes**
Modifies the Kernel.json artifact, adding a new role with the name `Manage profile` and id `MANAGE_PROFILE_ROLE`.

**If you are modifying the external API of one of the modules, please remember to also change the [documentation](/docs/)**

- [x] I have updated the associated documentation with my changes

### CODE REVIEW

**Comment by Evalir** [comment]
Yeah, for now, let's add (re-add? I remember seeing a (very funny) HACKS.md file before 😃) a HACKS.md file so people are aware.

**Comment by sohkai** [comment]
:+1: We can do so in a separate PR. That used to be in the aragon/aragon repo and was removed because we had no leftover hacks to document, but we can introduce it here to keep track of things like this.

**Comment by cygnusv** [comment]
Is there any documentation anywhere of what this role does?

**Comment by sohkai** [comment]
@cygnusv Not really; this was a "fake" role that we used for setting up DAO profiles on apiary.

**Pull request merged**
