### PR TITLE
Implement radspec postprocessing for humanizing addresses and roles

### PR DESCRIPTION
**Pull request by izqui**
This is sort of a temporary hack as this should probably be built as an extension to radspec in some way, but I'd like to have a bit more of time to think about how that API would look like. Also in the case of addresses we will probably want to do this directly in the client so we can show the entity component.

I'm having doubts about putting the replacements in quotes as you can see in the screenshot, do you think it would look better if we made the text bold @jounih?

Before:
2018-10-26 at 11 37 20 am

After:
2018-10-26 at 11 53 52 am

### CODE REVIEW

**Comment by jounih** [comment]
Yes it would be more readable to have those in bold I think

**Comment by izqui** [comment]
Good idea @bpierre, added 693bd49 with an implementation of `annotatedDescription`. It is added to the returned object in `describeTransactionPath`.

For this description: 

```
Grants 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF the ability to perform actions of role 0x0b719b33c83b8e5d300c521cb8b54ae9bd933996a14bef8c2f4e0285d2d2400a on 0x2a9446C6721fE12dFACA23b8e86fcFE2C778a7b3
```

It returns this annotated description:

```
[
  { "type": "text", "value": "Grants" },
  { "type": "any-account" },
  { "type": "text", "value": "the ability to perform actions of role" },
  { "type": "role", "role": {
      "name": "Create permissions",
      "id": "CREATE_PERMISSIONS_ROLE",
      "bytes": "0x0b719b33c83b8e5d300c521cb8b54ae9bd933996a14bef8c2f4e0285d2d2400a"
    }
  },
  { "type": "text", "value": "on" },
  { "type": "app", "app": {...} } // App object
]
```

And this processed description:
```
Grants 'Any account' the ability to perform actions of role 'Create permissions' on 'ACL'
```

**Comment by sohkai** [comment]
@bpierre the last commit changed the API of the annotated descriptions, such that in the above example (`Grants 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF the ability to perform actions of role 0x0b719b33c83b8e5d300c521cb8b54ae9bd933996a14bef8c2f4e0285d2d2400a on 0x2a9446C6721fE12dFACA23b8e86fcFE2C778a7b3`), it would give you the following:

```js
[
  { "type": "text", "value": "Grants" },
  { "type": "any-account", "value": "0xfff..." },
  { "type": "text", "value": "the ability to perform actions of role" },
  { "type": "role", "value": {
      "name": "Create permissions",
      "id": "CREATE_PERMISSIONS_ROLE",
      "bytes": "0x0b719b33c83b8e5d300c521cb8b54ae9bd933996a14bef8c2f4e0285d2d2400a"
    }
  },
  { "type": "text", "value": "on" },
  { "type": "app", "value": {...} } // App object
]
```

Every annotation node is just "type" and "value" rather than a different key based on the type.

**Comment by izqui** [comment]
Tested and working well. Nice improvement!

**Pull request merged**
